### ISSUE TITLE
Support Volume Keys

### ISSUE THREAD

**Issue by xmha97** [babydots/babybook#8]
Please support volume keys to go to next/previous page.

**Comment by pserwylo** [comment]
Sounds like a great idea, thanks for the recommendation. I think it should also support swiping - I've watched a couple of friends use the app, and their first instinct is always to swipe. Although I don't normally like a crazy amount of settings in my apps, I think it may be appropriate to have one which lets people choose their preferred way to move pages (or multiple ways).

**Comment by pserwylo** [comment]
Fixed in https://github.com/babydots/babybook/releases/tag/v0.7.0. Will be built and released by F-Droid in due course. I'll upload to Google Play soon.
